marks=[]
a=int(input("enter Marks: "))
marks.append(a)
b=int(input("enter Marks: "))
marks.append(b)
c=int(input("enter Marks: "))
marks.append(c)
d=int(input("enter Marks: "))
marks.append(d)
e=int(input("enter Marks: "))
marks.append(e)
f=int(input("enter Marks: "))
marks.append(f)
g=int(input("enter Marks: "))
marks.append(g)
marks.sort()
print(marks)
