set=set()
n=int(input("enter number: "))
set.add(n)
n=int(input("enter number: "))
set.add(n)
n=int(input("enter number: "))
set.add(n)
n=int(input("enter number: "))
set.add(n)
n=int(input("enter number: "))
set.add(n)
n=int(input("enter number: "))
set.add(n)
n=int(input("enter number: "))
set.add(n)
n=int(input("enter number: "))
set.add(n)
print(set)